export { default as Home } from './Home'
export { default as Products } from './Products'
export { default as Subcategories } from './Subcategories'
export { default as ProductsList } from './ProductsList'
export {default as Account} from './Acount'
export { default as Product } from './Product'
export { default as AboutPage } from './AboutPage'
export { default as ContactPage } from './ContactPage'
export { default as Cart } from './Cart'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Checkout } from './Checkout'
export { default as Orders } from './Orders'
export { default as OrderDetails } from './OrderDetails'


export { default as PageNotFound } from './PageNotFound'
