name: Deploy React App to FTP Server (Developer)

on:
  push:
    branches:
      - developer

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Set up .env for Developer
      run: cp .env.developer .env

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: vt000269.ferozo.com
        username: ftp@vt000269.ferozo.com
        password: 19tozuBUno
        local-dir: build/
        server-dir: public_html/
        exclude: |
          **/.git*
          **/.github*
